global:
  scrape_interval: 5s

remote_write:
  - url: "http://localhost:9090/api/v1/write"

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
