server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200 # 최대 워커 스레드 수 (default : 200)
      min-spare: 10 # 최소 유지 스레드 수 (default : 10)
    connection-timeout: 1m # 연결 타임아웃 (ms) (default : 60000ms = 1m)
    max-connections: 8192 # 최대 동시 연결 수 (default : 8192)
    accept-count: 100 # 대기 큐 크기 (default : 100)
    keep-alive-timeout: 60s # 60s
  max-http-request-header-size: 8KB

spring:
  main:
    web-application-type: servlet
  application:
    name: commerce-api
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - redis.yml
      - logging.yml
      - monitoring.yml

springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html

resilience4j:
  circuitbreaker:
    instances:
    # 'pg-payment' 라는 이름의 서킷 브레이커 설정
      pg-payment:
        sliding-window-size: 10         # 최근 10번 호출 기록을 샘플로 사용
        failure-rate-threshold: 50      # 실패율이 50% 이상이면 서킷 오픈
        wait-duration-in-open-state: 10s  # 서킷 오픈 후, 다음 시도를 허용하기 전 대기 시간 10초
        permitted-number-of-calls-in-half-open-state: 3  # half-open 상태에서 최대 3회 호출 허용
        slow-call-duration-threshold: 10s  # 3초 이상 걸리면 느린 호출로 간주
        slow-call-rate-threshold: 50      # 느린 호출 비율이 50% 이상이면 서킷 오픈 조건 포함
        sliding-window-type: time_based
        record-exceptions:
          - java.lang.Throwable
  retry:
    instances:
      pg-payment:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.lang.RuntimeException
          - java.util.concurrent.TimeoutException
          - feign.RetryableException
          - java.lang.IllegalArgumentException

logging:
  level:
    io.github.resilience4j.circuitbreaker: TRACE

---
spring:
  config:
    activate:
      on-profile: local, test

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd

springdoc:
  api-docs:
    enabled: false
